### ISSUE TITLE
Skipping temp files

### ISSUE THREAD

**Issue by dev1ant** [vmware/pg_rewind#49]
In master this has been fixed in another way in [this](http://www.postgresql.org/message-id/CAB7nPqRXx94WX2wwanEhthHQTSTZkqQ-xsW9==ysXVT9KZ+WwA@mail.gmail.com) thread.
Back-porting it to older branches is impossible since it needs a new feature in core.
Two other ways for solving this problem (plpgsql and copy/pasted new functions in the extension) seems too complicated. Maybe in older versions we could just skip all files that are known as temporary for us?

Most of the pg_rewind failures in my tests were the following:

1. `pg_xlog/xlogtemp` files, fixed [https://github.com/vmware/pg_rewind/issues/45](here),
2. Temporary tables:
```
error reading xlog record: record with zero length at 0/78000090
unexpected result while fetching remote files: ERROR:  could not open file "base/13003/t6_2424967" for reading: No such file or directory
The servers diverged at WAL position 0/76BADD50 on timeline 303.
Rewinding from Last common checkpoint at 0/7651F870 on timeline 303
```
3. `pg_internal.init`(I've caught it on several databases and it always happened for `postgres` DB):
```
error reading xlog record: record with zero length at 1/7D000090
unexpected result while fetching remote files: ERROR:  could not open file "base/13003/pg_internal.init" for reading: No such file or directory
The servers diverged at WAL position 1/7B7668A8 on timeline 690.
Rewinding from Last common checkpoint at 1/7B749560 on timeline 690
```

I also wonder why it is not possible to run pg_rewind one more time after failing in such cases (it fails with `unexpected control file size 0, expected 8192`)? Is it unsafe?

**Comment by michaelpq** [comment]
Actually I am going to work on those things very soon as I need a solution for 9.4. 9.3 will be backpatched accordingly. The idea is to integrate an extension that contains the set of functions necessary to be able to skip those race conditions similarly to what we did upstream. If the extension is not installed in the database that pg_rewind connects to in stream mode, it will simply fail.

I am also thinking that the patch upstream to ignore completely pg_xlog should be incorporated as well. It seems better to be consistent here.

**Comment by michaelpq** [comment]
Regarding the control file size, I think that we are missing an exit somewhere when we find a temp file causing an error when fetching chunks. I'll double-check.

**Comment by dev1ant** [comment]
Thank you very much, Michael. Looking forward to it.

**Comment by michaelpq** [comment]
OK, so I have pushed a set of improvements for all those things:
- Addition of pg_rewind_support which includes a set of C functions that are used by pg_rewind internally to not fail in case of missing files on source
- Make pg_rewind use that, by creating the set of functions in a dedicated schema and drop them once rewind is done.
Regression tests are passing for me. Let me know if there are extra problems.

**Comment by man-brain** [comment]
Thanks a lot! I'll test it.

**Comment by michaelpq** [comment]
I think I have fixed as well the problem you mentioned about control files being corrupted. Don't hesitate to reopen tickets if needed.

**Comment by man-brain** [comment]
Seems, that now it works as expected. Thanks.

The only problem I have found is that you can't run two concurrent pg_rewinds on different hosts now because you can't guarantee the order of creating/dropping schemas/functions by them on new master host. The use case for that is the following, for example. Host A is master, hosts B is synchronous standby, host C is async standby. Host A fails, host B is promoted but xlog position on host C is higher than was on host B so you can't just change recovery.conf on host C and make it standy of host B. You return host A as standby of host B with pg_rewind. And for host C you stop PostgreSQL, remove recovery.conf, start it to reach consistent state and stop it cleanly. At this point host C is cleanly shut down "master" on the old timeline and you return it to cluster as standby of host B with pg_rewind. And if both pg_rewinds (for host A and host C) are running simultaneously, one of them may fail.

 But that does not seem to be the problem of pg_rewind. I'll just force them to do it sequentially.
